server:
  port: 8088


  # DataSource Config
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/quotes-test?allowPublicKeyRetrieval=true&useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai&rewriteBatchedStatements=true
    username: root
    password: 123456

  servlet:
    multipart:
      max-file-size: 1MB

  redis:
    host: localhost
    port: 6379
    lettuce:
      pool:
        max-active: 50
        max-idle: 40
        min-idle: 10
        max-wait: 3000

mybatis-plus:
  mapper-locations: classpath*:com/github/Lisim2023/quotes/test/modules/**/xml/*Mapper.xml
  global-config:
    db-config:
      id-type: assign_uuid
      logic-delete-field: del_flag
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

